version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: release-it
    versions:
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
    - 14.6.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.24.0
    - 7.25.0
    - 7.26.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ember-source
    versions:
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.4.0
    - 5.5.0
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: "@clark/eslint-config-ember"
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: "@clark/eslint-config-ember-typescript"
    versions:
    - 2.0.0
    - 2.1.0
